* Red Teaming
** Definition
Testing your own organization of the unexpected by acting as a simulated adversary, 
in a simulated attack within a set amount of time.

*** What it is not

Exploiting everything we can find - probably not, there can be honeypots on the network.
If the action is not going to take us closer to the objective, let's not pursue it,
we cannot go everywhere due to limited time.

*** Cleaning up after the engagement

Cleaning up may not be necessary - depending on the engagement.

If you do a full clean up afterwards, it's going to be harder 
for the blue team to investigate. Part of the blue team workshop
should be to train the team. 

This can depend on the maturity of the target organization, 
to see if they are shipping logs and can search from that.

** Models - Killchains

*** Lockheed Martin killchain
A popular model, waterfall based.

*** SWC killchain
Specific for Microsoft solution, has some cycles in it, focused on Windows domains.

- first is low privilege, lateral movement, escalation cycle
- next is high privilege, lateral movement, escalation cycle

*** Mitre att&ck framework

Tactics, techniques, mostly from the blue team perspective

*** Core Red-Teaming / TNE cycle

1. Gather information (passive)
   + Enumerate systems, services, ports
   + Collect info from them
2. Combine existing information
   + Prepare exploit
   + Evade A/V
   + Prepare phishing scenario
3. Execute attack (active)
   + Execute an exploit
   + Send a phish
   + Collect new information
4. Using the newly obtained access / information / foothold, go back to 1

** TNE

*** Connecting to the network

**** Blending in
1. Try not to stand out
   + Using a hostname that doesn't stand out
   + Using a MAC that doesn't stand out

**** High-level approach
+ Passively connect to the network and monitor the traffic
+ Analyze the traffic to identify hostname convention, MAC family & vendor, DHCP settings

**** disable dhcp, disable network manager, so we don't request DHCP
+ systemctl

***** TODO netdiscover - shows which mac addresses are connected to which hosts
***** TODO networkminer - analyze pcap capture, can show hosts, images, messages, credentials
***** TODO macchanger - change MAC address, to spoof another device
***** TODO dhclient - configure DHCP

**** Checklist before connecting
+ disable dhcp
  * systemctl stop
+ disable network manager
+ don't use the same network interface from your laptop, if using VM, use and external USB network adapter
+ reboot system after changing the hostname
+ do all the above before connecting the cable
+ make sure no interfaces are autoconfigured to avoid alerting the blue team

**** Report tracking
+ make notes with what MAC address was used, which hostname was used, dhcp, timestamps

*** Information gathering

**** Test systems
Test instances are very interesting to hackers, as they are not monitored as much as production systems.
Test domains could also be useful due to password reuse

**** Who's who system is useful to spot administrators (system/db/...)

***** TODO nmap :: port scanner
+ could be made stealthy with the right options, some scans are risky
+ think about ports you'd like to scan to give you usable information
  * potentially interesting ports, like 80 (web server), if ssh is at 22, it already tells us it's linux, 3389 tell us there is RDP 
+ *don't scan too fast*, especially over routers or subnets - throttle
+ syn scans don't show up in the logs of devices, but in logs of the *routers*
+ can also try to scan for gateways to locate live IP ranges
+ port scan usually from one host (why?)

**** TODO responder
[[https://tools.kali.org/sniffingspoofing/responder][Kali docs on responder]]
Responds to name resolutions - specific netbios resolutions
Lot of broadcast traffic on the internet. 

*The objective is to make systems connect to you*, preferrably in a way that includes authentication.

+ Example - proxy discovery / autoconfiguration

+ NTLMv2 hash capture -> cracking
+ If the server requires SMB signing, then MITM is harder (but they say there are still tricks around that)

**** TODO ntlmrelay to reflect 
[[https://byt3bl33d3r.github.io/practical-guide-to-ntlm-relaying-in-2017-aka-getting-a-foothold-in-under-5-minutes.html][Guide to NTLM relaying]]


** General RTO Tips
+ You should have an online presence to back your story up
(in case the receptionist googles you)

+ Gain - we can capitalize from the victiom
  * Directly - capturing funds 
  * Indirectly - capturing information we can sell for funds

+ Make the organization more secure than the next one - locked bicycle example, as the one next to yours which looks less secure is more likely to be stolen

+ Default passwords are your friends
